apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-busted-rule
  namespace: default
spec:
  destination:
    name: reviews 
    namespace: default
  httpFault:
    abort:
      percent: 100 
      httpStatus: 500
